object OOFTF {

    const val HiHttp = "com.github.ooftf:hi-http:4.2.7"
    const val progressDrawable = "com.github.ooftf:progress-drawable:1.2.0"
    const val CalendarView = "com.github.ooftf:CalendarView:1.0.5"
    const val kvLayout = "com.github.ooftf:kv-layout:1.0.9"
    const val imagePreview = "com.github.ooftf:image-preview:2.3.1"
    const val basic = "com.github.ooftf:basic:0.4.2"
    const val afm = "com.github.ooftf:arch-frame-mvvm:0.2.2"
    const val statelayout = "com.github.ooftf:master-widget-statelayout:1.1.3"
    const val toolbar = "com.github.ooftf:master-widget-toolbar:1.1.8"
    const val dataBindingEx = "com.github.ooftf:dataBinding-extensions:1.2.6"
    const val tablayoutPro = "com.github.ooftf:tablayout-pro:0.0.3"
    const val dialog = "com.github.ooftf:master-widget-dialog:1.2.4"
    const val HttpUiMapping = "com.github.ooftf:http-ui-mapping:1.4.2"
    const val log = "com.github.ooftf:JLog:1.0.0"
    const val OperationEditTextLayout = "com.github.ooftf:OperationEditTextLayout:1.1.4"
    const val barrageView = "com.github.ooftf:BarrageView:1.1.0"
    const val bottomBar = "com.github.ooftf:bottom-bar:1.3.1"
    const val verticalPagerLayout = "com.github.ooftf:VerticalPagerLayout:2.0.0"
    const val support = "com.github.ooftf:Support:1.1.1"
    const val dockingApi = "com.github.ooftf:docking-api:3.0.0"
    const val share = "com.github.ooftf:hi-share:2.0.0"
    const val loadingView = "com.github.ooftf:loading-view:0.0.1"
    const val gsonAdapterExtensions = "com.github.ooftf:gson-adapter-extensions:0.0.4"

    const val spialeLayout = "com.github.ooftf:SpialeLayout:1.1.2"
    const val patternLock = "com.github.ooftf:PatternLock:1.0.4"
    const val straightLayout = "com.github.ooftf:StraightLayout:1.0.3"
    const val slidingLayout = "com.ooftf:sliding-layout:1.1.2"
    const val director = "com.github.ooftf:director:1.3.3"

}